json.id financial_asset.id
json.name financial_asset.name
json.ticker financial_asset.ticker
json.description financial_asset.description
json.asset_class financial_asset.asset_class
json.latest_price financial_asset.latest_price